import { accessContext } from './access';
import { audit } from './audit';
import { sql } from './db';
import { badRequest, forbidden, notFound, ok, serverError, unauthorized } from './http';

async function editor(){const a=await accessContext();if(!a)return null;return a.isPlatformAdmin||a.memberships.some((m:any)=>m.organization_kind==='internal'&&m.role==='content_editor')?a:null;}
async function body(request:Request){try{return await request.json() as any;}catch{throw new Error('Invalid JSON request body');}}
const kinds=new Set(['insight','case_study','career','page']);

export async function contentItem(request:Request){try{const a=await editor();if(!a)return unauthorized('Content editor access required');const u=new URL(request.url),kind=u.searchParams.get('kind')||'',id=u.searchParams.get('id')||'';if(!kinds.has(kind)||!/^\d+$/.test(id))return badRequest('Invalid content reference');let x:any;
if(kind==='insight'){x=(await sql`SELECT * FROM insight_posts WHERE id=${id} LIMIT 1`)[0];if(x)x={id:String(x.id),kind,title:x.title,slug:x.slug,status:x.status,summary:x.excerpt,body:x.body,aux1:x.category||'',aux2:'',tags:x.tags||[],featured:!!x.featured,active:true,closesAt:null,publishedAt:x.published_at,seoTitle:'',seoDescription:''};}
else if(kind==='case_study'){x=(await sql`SELECT * FROM case_studies WHERE id=${id} LIMIT 1`)[0];if(x)x={id:String(x.id),kind,title:x.title,slug:x.slug,status:x.status,summary:x.challenge,body:x.solution,aux1:x.client_label||'',aux2:x.industry||'',tags:x.services||[],featured:!!x.featured,active:true,closesAt:null,publishedAt:x.published_at,seoTitle:'',seoDescription:x.outcome||''};}
else if(kind==='career'){x=(await sql`SELECT * FROM career_openings WHERE id=${id} LIMIT 1`)[0];if(x)x={id:String(x.id),kind,title:x.title,slug:x.slug,status:x.active?'active':'inactive',summary:x.summary,body:x.description,aux1:x.location||'',aux2:x.employment_type||'',tags:[],featured:false,active:!!x.active,closesAt:x.closes_at,publishedAt:x.posted_at,seoTitle:'',seoDescription:''};}
else{x=(await sql`SELECT * FROM content_pages WHERE id=${id} LIMIT 1`)[0];if(x)x={id:String(x.id),kind,title:x.title,slug:x.slug,status:x.status,summary:x.summary||'',body:x.body,aux1:x.eyebrow||'',aux2:'',tags:[],featured:false,active:true,closesAt:null,publishedAt:x.published_at,seoTitle:x.seo_title||'',seoDescription:x.seo_description||''};}
if(!x)return notFound('Content not found');return ok({item:x},{headers:{'Cache-Control':'no-store'}});}catch(e){return serverError(e);}}

export async function contentUpdate(request:Request){try{const a=await editor();if(!a)return forbidden('Content editor access required');const b=await body(request);if(!kinds.has(b.kind)||!b.id||!b.title||!b.slug)return badRequest('Invalid content update');let rows:any[]=[];
if(b.kind==='insight')rows=await sql`UPDATE insight_posts SET title=${b.title},slug=${b.slug},excerpt=${b.excerpt??b.summary??''},body=${b.body??''},category=${b.category||null},tags=${b.tags||[]},featured=${!!b.featured},updated_at=now() WHERE id=${b.id} RETURNING id`;
else if(b.kind==='case_study')rows=await sql`UPDATE case_studies SET title=${b.title},slug=${b.slug},client_label=${b.clientLabel||null},industry=${b.industry||null},challenge=${b.challenge??b.summary??''},solution=${b.solution??b.body??''},outcome=${b.outcome??b.seoDescription??''},services=${b.services||b.tags||[]},featured=${!!b.featured},updated_at=now() WHERE id=${b.id} RETURNING id`;
else if(b.kind==='career')rows=await sql`UPDATE career_openings SET title=${b.title},slug=${b.slug},location=${b.location||null},employment_type=${b.employmentType||null},summary=${b.summary??''},description=${b.description??b.body??''},active=${b.active!==false},closes_at=${b.closesAt||null} WHERE id=${b.id} RETURNING id`;
else rows=await sql`UPDATE content_pages SET title=${b.title},slug=${b.slug},summary=${b.summary||null},body=${b.body??''},eyebrow=${b.eyebrow||null},seo_title=${b.seoTitle||null},seo_description=${b.seoDescription||null},updated_at=now() WHERE id=${b.id} RETURNING id`;
if(!rows.length)return notFound('Content not found');await audit(request,{userId:a.user.id,action:'content.updated',entityType:b.kind,entityId:b.id,metadata:{slug:b.slug}});return ok({ok:true});}catch(e){return serverError(e);}}

export async function contentStatus(request:Request){try{const a=await editor();if(!a)return forbidden('Content editor access required');const b=await body(request);if(!kinds.has(b.kind)||!b.id||!b.action)return badRequest('Invalid content status request');const now=new Date(),publishAt=b.publishAt?new Date(b.publishAt):null;if(b.action==='schedule'&&(!publishAt||publishAt<=now))return badRequest('Scheduled publication must be in the future');let rows:any[]=[];
if(b.kind==='career'){if(b.action==='activate')rows=await sql`UPDATE career_openings SET active=true WHERE id=${b.id} RETURNING id`;else if(b.action==='deactivate')rows=await sql`UPDATE career_openings SET active=false WHERE id=${b.id} RETURNING id`;else return badRequest('Unsupported action');}
else if(b.kind==='insight'){if(b.action==='publish')rows=await sql`UPDATE insight_posts SET status='published',published_at=now(),updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='unpublish')rows=await sql`UPDATE insight_posts SET status='draft',published_at=NULL,updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='submit_review')rows=await sql`UPDATE insight_posts SET status='review',updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='schedule')rows=await sql`UPDATE insight_posts SET status='scheduled',published_at=${publishAt},updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='archive')rows=await sql`UPDATE insight_posts SET status='archived',updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='feature')rows=await sql`UPDATE insight_posts SET featured=true,updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='unfeature')rows=await sql`UPDATE insight_posts SET featured=false,updated_at=now() WHERE id=${b.id} RETURNING id`;else return badRequest('Unsupported action');}
else if(b.kind==='case_study'){if(b.action==='publish')rows=await sql`UPDATE case_studies SET status='published',published_at=now(),updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='unpublish')rows=await sql`UPDATE case_studies SET status='draft',published_at=NULL,updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='submit_review')rows=await sql`UPDATE case_studies SET status='review',updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='schedule')rows=await sql`UPDATE case_studies SET status='scheduled',published_at=${publishAt},updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='archive')rows=await sql`UPDATE case_studies SET status='archived',updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='feature')rows=await sql`UPDATE case_studies SET featured=true,updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='unfeature')rows=await sql`UPDATE case_studies SET featured=false,updated_at=now() WHERE id=${b.id} RETURNING id`;else return badRequest('Unsupported action');}
else{if(b.action==='publish')rows=await sql`UPDATE content_pages SET status='published',published_at=now(),reviewer_user_id=${a.user.id},updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='unpublish')rows=await sql`UPDATE content_pages SET status='draft',published_at=NULL,updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='submit_review')rows=await sql`UPDATE content_pages SET status='review',updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='schedule')rows=await sql`UPDATE content_pages SET status='scheduled',published_at=${publishAt},reviewer_user_id=${a.user.id},updated_at=now() WHERE id=${b.id} RETURNING id`;else if(b.action==='archive')rows=await sql`UPDATE content_pages SET status='archived',updated_at=now() WHERE id=${b.id} RETURNING id`;else return badRequest('Unsupported action');}
if(!rows.length)return notFound('Content not found');await audit(request,{userId:a.user.id,action:`content.${b.action}`,entityType:b.kind,entityId:b.id,metadata:{publishAt:b.publishAt||null}});return ok({ok:true});}catch(e){return serverError(e);}}
