import { issueSignedToken, presignUrl } from '@vercel/blob';
import { randomBytes } from 'crypto';
import { accessContext } from './access';
import { audit } from './audit';
import { sql } from './db';
import { badRequest, forbidden, notFound, ok, serverError, unauthorized } from './http';

function blobToken(){const t=process.env.BLOB_READ_WRITE_TOKEN;if(!t)throw new Error('Vercel Blob is not configured');return t;}
async function admin(){const a=await accessContext();return a?.isPlatformAdmin?a:null;}
async function recruitment(){const a=await accessContext();if(!a)return null;return a.isPlatformAdmin||a.memberships.some((m:any)=>m.organization_kind==='internal'&&m.role==='executive')?a:null;}
async function body(request:Request){try{return await request.json() as any;}catch{throw new Error('Invalid JSON request body');}}
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,55)||'client';}

export async function handleAdminExtendedGET(path:string,request:Request):Promise<Response|null>{
  try{
    if(path==='career-resume'){
      const a=await recruitment();if(!a)return unauthorized('Recruitment access required');const applicationId=new URL(request.url).searchParams.get('applicationId');if(!applicationId||!/^\d+$/.test(applicationId))return badRequest('Invalid application');const rows=await sql`SELECT resume_storage_key FROM career_applications WHERE id=${applicationId} LIMIT 1`;const key=rows[0]?.resume_storage_key;if(!key)return notFound('No résumé is attached');const fallback=String(key).match(/^dbresume:(\d+)$/);if(fallback){const blob=await sql`SELECT id FROM career_resume_blobs WHERE id=${fallback[1]} AND application_id=${applicationId} LIMIT 1`;if(!blob.length)return notFound('Résumé file is unavailable');await audit(request,{userId:a.user.id,action:'career_application.resume_viewed',entityType:'career_application',entityId:applicationId,metadata:{storage:'database_fallback'}});return ok({url:`/api/admin/career-resume-file?applicationId=${encodeURIComponent(applicationId)}`},{headers:{'Cache-Control':'no-store'}});}const signed=await issueSignedToken({pathname:String(key),operations:['get'],validUntil:Date.now()+60*60*1000,token:blobToken()});const {presignedUrl}=await presignUrl(signed,{operation:'get',pathname:String(key),access:'private',validUntil:Date.now()+5*60*1000});await audit(request,{userId:a.user.id,action:'career_application.resume_viewed',entityType:'career_application',entityId:applicationId});return ok({url:presignedUrl},{headers:{'Cache-Control':'no-store'}});
    }
    if(path==='career-resume-file'){
      const a=await recruitment();if(!a)return new Response('Recruitment access required',{status:403});const applicationId=new URL(request.url).searchParams.get('applicationId');if(!applicationId||!/^\d+$/.test(applicationId))return new Response('Invalid application',{status:400});const rows=await sql`SELECT resume_storage_key FROM career_applications WHERE id=${applicationId} LIMIT 1`;const blobId=String(rows[0]?.resume_storage_key||'').match(/^dbresume:(\d+)$/)?.[1];if(!blobId)return new Response('Résumé file is unavailable',{status:404});const blobs=await sql`SELECT data,file_name,content_type,size_bytes FROM career_resume_blobs WHERE id=${blobId} AND application_id=${applicationId} LIMIT 1`;if(!blobs.length)return new Response('Résumé file is unavailable',{status:404});const b:any=blobs[0];const safe=String(b.file_name).replace(/["\r\n]/g,'-');return new Response(b.data,{headers:{'Content-Type':b.content_type,'Content-Length':String(b.size_bytes),'Content-Disposition':`inline; filename="${safe}"`,'Cache-Control':'private, no-store, max-age=0','X-Content-Type-Options':'nosniff'}});
    }
    if(path==='inquiry-detail'){
      const a=await admin();if(!a)return forbidden('Administrator access required');const id=new URL(request.url).searchParams.get('inquiryId')||'';if(!/^\d+$/.test(id))return badRequest('Invalid inquiry');const rows=await sql`SELECT i.id::text,i.reference_code,i.full_name,i.work_email,i.phone,i.company_name,i.job_title,i.country_code,i.service_code,i.budget_band,i.timeline,i.message,i.status,i.assigned_user_id::text,i.source,i.consent_marketing,i.created_at,i.updated_at,i.converted_engagement_id::text,u.display_name AS assigned_user_name,e.code AS converted_engagement_code FROM contact_inquiries i LEFT JOIN users u ON u.id=i.assigned_user_id LEFT JOIN engagements e ON e.id=i.converted_engagement_id WHERE i.id=${id} LIMIT 1`;if(!rows.length)return notFound('Inquiry not found');const [notes,assignees]=await Promise.all([sql`SELECT n.id::text,n.body,n.created_at,u.display_name AS author FROM inquiry_notes n JOIN users u ON u.id=n.author_user_id WHERE n.inquiry_id=${id} ORDER BY n.created_at DESC`,sql`SELECT u.id::text,u.display_name,u.email FROM users u JOIN organization_memberships m ON m.user_id=u.id JOIN organizations o ON o.id=m.organization_id WHERE u.active=true AND m.active=true AND o.active=true AND o.kind='internal' GROUP BY u.id,u.display_name,u.email ORDER BY u.display_name`]);return ok({inquiry:rows[0],notes,assignees},{headers:{'Cache-Control':'no-store'}});
    }
    return null;
  }catch(error){console.error('Admin extended GET failed',path,error);return serverError(error);}
}

export async function handleAdminExtendedPOST(path:string,request:Request):Promise<Response|null>{
  try{
    if(path==='inquiry-update'){
      const a=await admin();if(!a)return forbidden('Administrator access required');const b=await body(request);if(!b.inquiryId||!b.status)return badRequest('inquiryId and status are required');if(b.assignedUserId){const eligible=await sql`SELECT u.id FROM users u JOIN organization_memberships m ON m.user_id=u.id JOIN organizations o ON o.id=m.organization_id WHERE u.id=${b.assignedUserId} AND u.active=true AND m.active=true AND o.active=true AND o.kind='internal' LIMIT 1`;if(!eligible.length)return badRequest('Assignee must be an active internal user');}const updated=await sql`UPDATE contact_inquiries SET status=${b.status},assigned_user_id=${b.assignedUserId||null},service_code=${b.serviceCode||null},budget_band=${b.budgetBand||null},timeline=${b.timeline||null},updated_at=now() WHERE id=${b.inquiryId} RETURNING id`;if(!updated.length)return notFound('Inquiry not found');await audit(request,{userId:a.user.id,action:'inquiry.qualified_context_updated',entityType:'contact_inquiry',entityId:b.inquiryId,metadata:{status:b.status,assignedUserId:b.assignedUserId||null,serviceCode:b.serviceCode||null,budgetBand:b.budgetBand||null,timeline:b.timeline||null}});return ok({ok:true});
    }
    if(path==='inquiry-convert'){
      const a=await admin();if(!a)return forbidden('Administrator access required');const b=await body(request);if(!b.inquiryId)return badRequest('inquiryId is required');const rows=await sql`SELECT * FROM contact_inquiries WHERE id=${b.inquiryId} LIMIT 1`;const i:any=rows[0];if(!i)return notFound('Inquiry not found');const clientName=String(i.company_name||`${i.full_name} Organization`).trim();let orgs=await sql`SELECT id::text,name FROM organizations WHERE kind='client' AND name ILIKE ${clientName} LIMIT 1`;let org:any=orgs[0];if(!org){const [created]=await sql`INSERT INTO organizations(name,slug,kind,country_code,active) VALUES (${clientName},${`${slugify(clientName)}-${randomBytes(2).toString('hex')}`},'client',${i.country_code||null},true) RETURNING id::text,name`;org=created;}if(i.converted_engagement_id){const existing=await sql`SELECT id::text,code FROM engagements WHERE id=${i.converted_engagement_id} LIMIT 1`;if(existing.length)return ok({engagementId:existing[0].id,engagementCode:existing[0].code,organizationId:org.id});}const dup=await sql`SELECT id::text,code FROM engagements WHERE client_organization_id=${org.id} AND summary ILIKE ${`%${i.reference_code}%`} LIMIT 1`;if(dup.length){await sql`UPDATE contact_inquiries SET converted_engagement_id=${dup[0].id},updated_at=now() WHERE id=${i.id}`;return ok({engagementId:dup[0].id,engagementCode:dup[0].code,organizationId:org.id});}const code=`CSE-${new Date().getUTCFullYear()}-${randomBytes(2).toString('hex').toUpperCase()}`;const title=b.engagementTitle||`${String(i.service_code||'CyberSE').replaceAll('_',' ')} — ${clientName}`;const summary=`Created from ${i.reference_code}. ${i.message}`;const [eng]=await sql`INSERT INTO engagements(code,client_organization_id,title,summary,status,priority,owner_user_id,created_by_user_id,confidentiality_level) VALUES (${code},${org.id},${title},${summary},'scoping',${b.priority||'normal'},${a.user.id},${a.user.id},'confidential') RETURNING id::text,code`;await sql`INSERT INTO engagement_members(engagement_id,user_id,responsibility,can_view_sensitive_findings,can_approve,active) VALUES (${eng.id},${a.user.id},'Engagement owner',true,true,true)`;if(i.service_code){const svc=await sql`SELECT id::text FROM service_catalog WHERE code=${i.service_code} LIMIT 1`;if(svc.length)await sql`INSERT INTO engagement_services(engagement_id,service_id,scope_summary) VALUES (${eng.id},${svc[0].id},${i.message})`;}await sql`UPDATE contact_inquiries SET status='discovery',assigned_user_id=${a.user.id},converted_engagement_id=${eng.id},updated_at=now() WHERE id=${i.id}`;await audit(request,{userId:a.user.id,organizationId:org.id,engagementId:eng.id,action:'inquiry.converted_to_engagement',entityType:'contact_inquiry',entityId:i.id,metadata:{referenceCode:i.reference_code,engagementCode:code}});return ok({engagementId:eng.id,engagementCode:code,organizationId:org.id});
    }
    if(path==='housekeeping'){
      const a=await admin();if(!a)return forbidden('Administrator access required');const b=await body(request);const counts=await sql`SELECT (SELECT count(*) FROM sessions WHERE expires_at<=now())::int AS expired_sessions,(SELECT count(*) FROM login_attempts WHERE attempted_at<now()-interval '30 days')::int AS old_login_attempts,(SELECT count(*) FROM public_rate_limit_events WHERE created_at<now()-interval '48 hours')::int AS old_public_rate_events,(SELECT count(*) FROM password_reset_tokens WHERE used_at IS NULL AND revoked_at IS NULL AND expires_at<=now())::int AS expired_reset_tokens,(SELECT count(*) FROM user_invitations WHERE accepted_at IS NULL AND revoked_at IS NULL AND expires_at<=now())::int AS expired_invitations,(SELECT count(*) FROM push_subscriptions WHERE active=false AND updated_at<now()-interval '90 days')::int AS old_inactive_push_subscriptions`;const c:any=counts[0];if(b.mode==='execute'){await sql.begin(async tx=>{await tx`DELETE FROM sessions WHERE expires_at<=now()`;await tx`DELETE FROM login_attempts WHERE attempted_at<now()-interval '30 days'`;await tx`DELETE FROM public_rate_limit_events WHERE created_at<now()-interval '48 hours'`;await tx`UPDATE password_reset_tokens SET revoked_at=now() WHERE used_at IS NULL AND revoked_at IS NULL AND expires_at<=now()`;await tx`UPDATE user_invitations SET revoked_at=now() WHERE accepted_at IS NULL AND revoked_at IS NULL AND expires_at<=now()`;await tx`DELETE FROM push_subscriptions WHERE active=false AND updated_at<now()-interval '90 days'`;});await audit(request,{userId:a.user.id,action:'platform.housekeeping_executed',entityType:'platform',entityId:'housekeeping',metadata:c});}return ok({mode:b.mode||'preview',expiredSessions:Number(c.expired_sessions),oldLoginAttempts:Number(c.old_login_attempts),oldPublicRateEvents:Number(c.old_public_rate_events),expiredResetTokens:Number(c.expired_reset_tokens),expiredInvitations:Number(c.expired_invitations),oldInactivePushSubscriptions:Number(c.old_inactive_push_subscriptions)},{headers:{'Cache-Control':'no-store'}});
    }
    return null;
  }catch(error){console.error('Admin extended POST failed',path,error);return serverError(error);}
}
