import { compare, hash } from 'bcryptjs';
import { issueSignedToken, presignUrl } from '@vercel/blob';
import { createHash, randomBytes } from 'crypto';
import { accessContext, authorizedEngagementScope } from './access';
import { audit } from './audit';
import { getSessionId } from './auth';
import { sql } from './db';
import { badRequest, conflict, forbidden, notFound, ok, serverError, unauthorized } from './http';

const deliveryRoles = ['platform_admin','project_manager','security_lead','security_consultant','software_engineer','risk_analyst'];
const riskRoles = ['platform_admin','project_manager','risk_analyst','security_lead'];
const reportRoles = ['platform_admin','project_manager','security_lead','security_consultant','risk_analyst'];
const findingRoles = ['platform_admin','project_manager','security_lead','security_consultant'];

async function body(request: Request) { try { return await request.json() as any; } catch { throw new Error('Invalid JSON request body'); } }
function scopeHas(scope: Awaited<ReturnType<typeof authorizedEngagementScope>>, id: unknown) { return !!scope && scope.engagementIds.includes(String(id)); }
function internal(scope: Awaited<ReturnType<typeof authorizedEngagementScope>>) { return !!scope && (scope.access.isPlatformAdmin || scope.access.memberships.some((m:any)=>m.organization_kind==='internal')); }
function role(scope: Awaited<ReturnType<typeof authorizedEngagementScope>>, roles:string[]) { return !!scope && (scope.access.isPlatformAdmin || scope.access.memberships.some((m:any)=>m.organization_kind==='internal'&&roles.includes(m.role))); }
function nextVersion(current:string){const m=current.match(/^(\d+)(?:\.(\d+))?$/);return m?`${Number(m[1])}.${Number(m[2]||0)+1}`:'1.1';}
function blobToken(){const token=process.env.BLOB_READ_WRITE_TOKEN;if(!token)throw new Error('Vercel Blob is not configured');return token;}

export async function handleExtendedDetailsGET(path:string,request:Request):Promise<Response|null>{
  try{
    if(path==='engagement-detail'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const id=new URL(request.url).searchParams.get('id');if(!id||!/^\d+$/.test(id))return badRequest('Invalid engagement');
      const [e]=await sql`SELECT e.id::text,e.code,e.title,e.summary,e.status,e.priority,e.start_date,e.target_end_date,e.confidentiality_level,e.client_organization_id::text,o.name AS client_name FROM engagements e JOIN organizations o ON o.id=e.client_organization_id WHERE e.id=${id} LIMIT 1`;if(!e)return notFound('Engagement not found');
      const member=await sql`SELECT id::text,can_view_sensitive_findings FROM engagement_members WHERE engagement_id=${id} AND user_id=${scope.access.user.id} AND active=true LIMIT 1`;
      const orgAllowed=scope.access.memberships.some((m:any)=>String(m.organization_id)===String(e.client_organization_id));if(!scope.access.isPlatformAdmin&&!orgAllowed&&!member.length)return forbidden();
      const isInternal=internal(scope);const sensitive=isInternal||member[0]?.can_view_sensitive_findings===true;
      const services=await sql`SELECT sc.name FROM engagement_services es JOIN service_catalog sc ON sc.id=es.service_id WHERE es.engagement_id=${id}`;
      const milestones=isInternal?await sql`SELECT id::text,title,description,due_date,completed_at FROM engagement_milestones WHERE engagement_id=${id} ORDER BY sort_order`:await sql`SELECT id::text,title,description,due_date,completed_at FROM engagement_milestones WHERE engagement_id=${id} AND client_visible=true ORDER BY sort_order`;
      const tasks=isInternal?await sql`SELECT id::text,title,status,priority,due_at FROM engagement_tasks WHERE engagement_id=${id} ORDER BY created_at DESC LIMIT 30`:await sql`SELECT id::text,title,status,priority,due_at FROM engagement_tasks WHERE engagement_id=${id} AND client_visible=true ORDER BY created_at DESC LIMIT 30`;
      const assessments=isInternal?await sql`SELECT id::text,title,assessment_type,status,planned_start_at,planned_end_at FROM assessments WHERE engagement_id=${id} ORDER BY created_at DESC`:await sql`SELECT id::text,title,assessment_type,status,planned_start_at,planned_end_at FROM assessments WHERE engagement_id=${id} AND client_visible=true ORDER BY created_at DESC`;
      const findings=sensitive?await sql`SELECT id::text,finding_code,title,severity,status,cvss_score,remediation_due_at FROM findings WHERE engagement_id=${id} ORDER BY discovered_at DESC LIMIT 50`:await sql`SELECT id::text,finding_code,title,severity,status,cvss_score,remediation_due_at FROM findings WHERE engagement_id=${id} AND client_visible=true ORDER BY discovered_at DESC LIMIT 50`;
      const risks=isInternal?await sql`SELECT id::text,risk_code,title,status,inherent_score,likelihood,impact,treatment FROM risk_items WHERE engagement_id=${id} ORDER BY inherent_score DESC LIMIT 50`:await sql`SELECT id::text,risk_code,title,status,inherent_score,likelihood,impact,treatment FROM risk_items WHERE engagement_id=${id} AND client_visible=true ORDER BY inherent_score DESC LIMIT 50`;
      const documents=isInternal?await sql`SELECT id::text,document_code,title,class,status,version_label,created_at FROM documents WHERE engagement_id=${id} ORDER BY created_at DESC LIMIT 50`:await sql`SELECT id::text,document_code,title,class,status,version_label,created_at FROM documents WHERE engagement_id=${id} AND client_visible=true ORDER BY created_at DESC LIMIT 50`;
      const reports=isInternal?await sql`SELECT id::text,title,report_type,status,version_label,issued_at FROM reports WHERE engagement_id=${id} ORDER BY created_at DESC`:await sql`SELECT id::text,title,report_type,status,version_label,issued_at FROM reports WHERE engagement_id=${id} AND client_visible=true ORDER BY created_at DESC`;
      const members=await sql`SELECT em.id::text,u.display_name,u.email,em.responsibility,em.can_approve FROM engagement_members em JOIN users u ON u.id=em.user_id WHERE em.engagement_id=${id} AND em.active=true`;
      return ok({engagement:e,services:services.map((x:any)=>x.name),milestones,tasks,assessments,findings,risks,documents,reports,members,canManage:scope.access.isPlatformAdmin||Boolean(member.length&&role(scope,deliveryRoles))},{headers:{'Cache-Control':'no-store'}});
    }

    if(path==='finding-detail'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const id=new URL(request.url).searchParams.get('id');if(!id||!/^\d+$/.test(id))return badRequest('Invalid finding');
      const [f]=await sql`SELECT f.id::text,f.engagement_id::text,e.code AS engagement_code,e.title AS engagement_title,o.name AS client_name,f.finding_code,f.title,f.severity,f.status,f.cvss_score,f.cwe_id,f.owasp_reference,f.description,f.impact,f.evidence_summary,f.recommendation,f.remediation_due_at,f.remediation_owner_user_id::text,ru.display_name AS remediation_owner_name,f.retest_result,f.retested_at,f.accepted_risk_reason,f.accepted_at,f.client_visible,f.discovered_at,f.closed_at FROM findings f JOIN engagements e ON e.id=f.engagement_id JOIN organizations o ON o.id=e.client_organization_id LEFT JOIN users ru ON ru.id=f.remediation_owner_user_id WHERE f.id=${id} LIMIT 1`;
      if(!f)return notFound('Finding not found');if(!scopeHas(scope,f.engagement_id))return forbidden();const isInternal=internal(scope);if(!isInternal&&!scope.sensitiveEngagementIds.includes(f.engagement_id)&&!f.client_visible)return forbidden('This finding has not been released to the client');
      const comments=isInternal?await sql`SELECT c.id::text,c.body,c.client_visible,c.created_at,u.display_name AS author_name FROM finding_comments c JOIN users u ON u.id=c.author_user_id WHERE c.finding_id=${id} ORDER BY c.created_at`:await sql`SELECT c.id::text,c.body,c.client_visible,c.created_at,u.display_name AS author_name FROM finding_comments c JOIN users u ON u.id=c.author_user_id WHERE c.finding_id=${id} AND c.client_visible=true ORDER BY c.created_at`;
      const evidence=isInternal?await sql`SELECT id::text,evidence_code,title,description,source,captured_at,document_id::text,integrity_hash FROM evidence_items WHERE finding_id=${id} ORDER BY created_at DESC`:await sql`SELECT id::text,evidence_code,title,description,source,captured_at,document_id::text,integrity_hash FROM evidence_items WHERE finding_id=${id} AND client_visible=true ORDER BY created_at DESC`;
      const assignees=await sql`SELECT em.user_id::text,u.display_name FROM engagement_members em JOIN users u ON u.id=em.user_id WHERE em.engagement_id=${f.engagement_id} AND em.active=true ORDER BY u.display_name`;
      return ok({finding:f,comments,evidence,assignees,canManage:role(scope,findingRoles)},{headers:{'Cache-Control':'no-store'}});
    }

    if(path==='risk-detail'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const id=new URL(request.url).searchParams.get('id');if(!id||!/^\d+$/.test(id))return badRequest('Invalid risk');
      const [r]=await sql`SELECT r.id::text,r.engagement_id::text,e.code AS engagement_code,e.title AS engagement_title,o.name AS client_name,r.risk_code,r.title,r.description,r.category,r.threat,r.vulnerability,r.asset_context,r.likelihood,r.impact,r.inherent_score,r.residual_likelihood,r.residual_impact,r.treatment,r.treatment_plan,r.owner_user_id::text,ou.display_name AS owner_name,r.status,r.target_date,r.review_date,r.accepted_at,r.client_visible FROM risk_items r JOIN engagements e ON e.id=r.engagement_id JOIN organizations o ON o.id=e.client_organization_id LEFT JOIN users ou ON ou.id=r.owner_user_id WHERE r.id=${id} LIMIT 1`;
      if(!r)return notFound('Risk not found');if(!scopeHas(scope,r.engagement_id))return forbidden();const isInternal=internal(scope);if(!isInternal&&!r.client_visible)return forbidden('This risk has not been released to the client');const canManage=role(scope,riskRoles);
      const controls=await sql`SELECT l.id::text AS link_id,c.id::text AS control_id,c.framework,c.control_code,c.title,c.domain,l.status,l.effectiveness_notes,l.assessed_at FROM risk_control_links l JOIN control_catalog c ON c.id=l.control_id WHERE l.risk_id=${id} ORDER BY c.framework,c.control_code`;
      const catalog=canManage?await sql`SELECT id::text,framework,control_code,title,domain FROM control_catalog WHERE active=true ORDER BY framework,control_code LIMIT 1000`:[];
      const evidence=isInternal?await sql`SELECT id::text,evidence_code,title,description,source,captured_at,integrity_hash FROM evidence_items WHERE risk_id=${id} ORDER BY created_at DESC`:await sql`SELECT id::text,evidence_code,title,description,source,captured_at,integrity_hash FROM evidence_items WHERE risk_id=${id} AND client_visible=true ORDER BY created_at DESC`;
      const assignees=canManage?await sql`SELECT em.user_id::text,u.display_name FROM engagement_members em JOIN users u ON u.id=em.user_id WHERE em.engagement_id=${r.engagement_id} AND em.active=true ORDER BY u.display_name`:[];
      return ok({risk:r,controls,catalog,evidence,assignees,canManage},{headers:{'Cache-Control':'no-store'}});
    }

    if(path==='report-detail'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const id=new URL(request.url).searchParams.get('id');if(!id||!/^\d+$/.test(id))return badRequest('Invalid report');
      const [r]=await sql`SELECT r.id::text,r.engagement_id::text,r.title,r.report_type,r.status,r.version_label,r.executive_summary,r.technical_summary,r.issued_at,r.client_visible,r.assessment_id::text,r.document_id::text,r.supersedes_report_id::text,e.code AS engagement_code,e.title AS engagement_title,o.name AS client_name,a.title AS assessment_title,d.title AS document_title,p.display_name AS prepared_by_name,rv.display_name AS reviewed_by_name,ap.display_name AS approved_by_name FROM reports r JOIN engagements e ON e.id=r.engagement_id JOIN organizations o ON o.id=e.client_organization_id LEFT JOIN assessments a ON a.id=r.assessment_id LEFT JOIN documents d ON d.id=r.document_id LEFT JOIN users p ON p.id=r.prepared_by_user_id LEFT JOIN users rv ON rv.id=r.reviewed_by_user_id LEFT JOIN users ap ON ap.id=r.approved_by_user_id WHERE r.id=${id} LIMIT 1`;
      if(!r)return notFound('Report not found');if(!scopeHas(scope,r.engagement_id))return forbidden();const isInternal=internal(scope);if(!isInternal&&!r.client_visible)return forbidden('This report has not been released to the client');const canManage=role(scope,reportRoles);
      const findings=isInternal?await sql`SELECT finding_code,title,severity,status,cvss_score,impact,recommendation FROM findings WHERE engagement_id=${r.engagement_id} AND status<>'false_positive' ORDER BY severity`:await sql`SELECT finding_code,title,severity,status,cvss_score,impact,recommendation FROM findings WHERE engagement_id=${r.engagement_id} AND status<>'false_positive' AND client_visible=true ORDER BY severity`;
      const risks=isInternal?await sql`SELECT risk_code,title,inherent_score,status,treatment,treatment_plan FROM risk_items WHERE engagement_id=${r.engagement_id} ORDER BY inherent_score DESC`:await sql`SELECT risk_code,title,inherent_score,status,treatment,treatment_plan FROM risk_items WHERE engagement_id=${r.engagement_id} AND client_visible=true ORDER BY inherent_score DESC`;
      const assessments=canManage?await sql`SELECT id::text,title,client_visible FROM assessments WHERE engagement_id=${r.engagement_id} ORDER BY created_at DESC`:[];
      const documents=canManage?await sql`SELECT id::text,title,document_code,status,client_visible FROM documents WHERE engagement_id=${r.engagement_id} AND class='report' ORDER BY created_at DESC`:[];
      return ok({report:r,findings,risks,assessments,documents,canManage},{headers:{'Cache-Control':'no-store'}});
    }

    if(path==='support-detail'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const id=new URL(request.url).searchParams.get('id');if(!id||!/^\d+$/.test(id))return badRequest('Invalid ticket');const actor=String(scope.access.user.id);
      const [t]=await sql`SELECT t.id::text,t.ticket_code,t.title,t.description,t.priority,t.status,t.engagement_id::text,t.opened_by_user_id::text,t.assigned_user_id::text,t.created_at,t.updated_at,o.name AS organization_name,e.code AS engagement_code,e.title AS engagement_title,op.display_name AS opened_by,au.display_name AS assigned_to FROM support_tickets t LEFT JOIN organizations o ON o.id=t.organization_id LEFT JOIN engagements e ON e.id=t.engagement_id JOIN users op ON op.id=t.opened_by_user_id LEFT JOIN users au ON au.id=t.assigned_user_id WHERE t.id=${id} LIMIT 1`;
      if(!t)return notFound('Ticket not found');const engagementAllowed=t.engagement_id?scopeHas(scope,t.engagement_id):false;const ops=role(scope,deliveryRoles);if(!scope.access.isPlatformAdmin&&t.opened_by_user_id!==actor&&!engagementAllowed&&!(ops&&!t.engagement_id))return forbidden();const isInternal=internal(scope);
      const comments=isInternal?await sql`SELECT c.id::text,c.body,c.internal_only,c.created_at,u.display_name AS author_name FROM ticket_comments c JOIN users u ON u.id=c.author_user_id WHERE c.ticket_id=${id} ORDER BY c.created_at`:await sql`SELECT c.id::text,c.body,c.internal_only,c.created_at,u.display_name AS author_name FROM ticket_comments c JOIN users u ON u.id=c.author_user_id WHERE c.ticket_id=${id} AND c.internal_only=false ORDER BY c.created_at`;
      const canManage=ops&&(!t.engagement_id||scope.access.isPlatformAdmin||engagementAllowed);let assignees:any[]=[];if(canManage){assignees=t.engagement_id?await sql`SELECT DISTINCT u.id::text AS user_id,u.display_name,u.email FROM engagement_members em JOIN users u ON u.id=em.user_id JOIN organization_memberships m ON m.user_id=u.id JOIN organizations o ON o.id=m.organization_id WHERE em.engagement_id=${t.engagement_id} AND em.active=true AND u.active=true AND m.active=true AND o.active=true AND o.kind='internal' ORDER BY u.display_name`:await sql`SELECT DISTINCT u.id::text AS user_id,u.display_name,u.email FROM organization_memberships m JOIN organizations o ON o.id=m.organization_id JOIN users u ON u.id=m.user_id WHERE m.active=true AND o.active=true AND o.kind='internal' AND u.active=true ORDER BY u.display_name`;}
      return ok({ticket:t,comments,canManage,canInternalComment:isInternal,assignees},{headers:{'Cache-Control':'no-store'}});
    }

    if(path==='security'){
      const access=await accessContext();if(!access)return unauthorized();const sessionId=await getSessionId();if(!sessionId)return unauthorized();const sessions=await sql`SELECT id,created_at,last_accessed,expires_at,user_agent,source_ip FROM sessions WHERE user_id=${access.user.id} AND expires_at>now() ORDER BY last_accessed DESC`;const password=await sql`SELECT updated_at FROM user_passwords WHERE user_id=${access.user.id} LIMIT 1`;const failed=await sql`SELECT count(*)::int AS count FROM login_attempts WHERE email=${access.user.email.toLowerCase()} AND success=false AND attempted_at>=now()-interval '24 hours'`;
      return ok({passwordChangedAt:password[0]?.updated_at||null,failedLogins24h:Number(failed[0]?.count||0),sessions:sessions.map((s:any)=>({handle:createHash('sha256').update(s.id).digest('hex'),createdAt:s.created_at,lastAccessed:s.last_accessed,expiresAt:s.expires_at,current:s.id===sessionId,userAgent:s.user_agent,sourceIp:s.source_ip}))},{headers:{'Cache-Control':'no-store'}});
    }

    if(path==='document-download'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const id=new URL(request.url).searchParams.get('id');if(!id||!/^\d+$/.test(id))return badRequest('Invalid document');const [d]=await sql`SELECT id::text,engagement_id::text,storage_key,file_name,content_type,client_visible FROM documents WHERE id=${id} LIMIT 1`;if(!d||!d.engagement_id||!d.storage_key)return notFound('Document not available');if(!scopeHas(scope,d.engagement_id))return forbidden();if(!d.client_visible&&!internal(scope))return forbidden();
      const signed=await issueSignedToken({pathname:d.storage_key,operations:['get'],validUntil:Date.now()+60*60*1000,token:blobToken()});const {presignedUrl}=await presignUrl(signed,{operation:'get',pathname:d.storage_key,access:'private',validUntil:Date.now()+5*60*1000});return ok({url:presignedUrl,fileName:d.file_name,contentType:d.content_type},{headers:{'Cache-Control':'no-store'}});
    }

    return null;
  }catch(error){console.error('Detailed portal GET failed',path,error);return serverError(error);}
}

export async function handleExtendedDetailsPOST(path:string,request:Request):Promise<Response|null>{
  try{
    if(path==='document-presign'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.engagementId||!input.fileName||!input.contentType||!input.sizeBytes)return badRequest('Missing upload metadata');if(!scopeHas(scope,input.engagementId))return forbidden();const max=20*1024*1024;if(Number(input.sizeBytes)>max)return badRequest('File exceeds the 20 MB upload limit');const clean=String(input.fileName).replace(/[^A-Za-z0-9._-]+/g,'-').replace(/^-+/g,'').slice(-160)||'file';const storageKey=`engagements/${input.engagementId}/documents/${Date.now()}-${randomBytes(6).toString('hex')}-${clean}`;
      const signed=await issueSignedToken({pathname:storageKey,operations:['put'],allowedContentTypes:[input.contentType],maximumSizeInBytes:Number(input.sizeBytes),validUntil:Date.now()+60*60*1000,token:blobToken()});const {presignedUrl}=await presignUrl(signed,{operation:'put',pathname:storageKey,access:'private',validUntil:Date.now()+15*60*1000,allowedContentTypes:[input.contentType],maximumSizeInBytes:Number(input.sizeBytes),addRandomSuffix:false,allowOverwrite:false});return ok({storageKey,presignedUrl});
    }

    if(path==='document-finalize'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.engagementId||!input.storageKey||!input.fileName||!input.title)return badRequest('Missing document metadata');if(!scopeHas(scope,input.engagementId))return forbidden();if(!String(input.storageKey).startsWith(`engagements/${input.engagementId}/documents/`))return badRequest('Invalid storage path');const isInternal=internal(scope);const clientVisible=isInternal?!!input.clientVisible:true;let superseded:any=null;if(input.supersedesDocumentId){const rows=await sql`SELECT id::text,version_label FROM documents WHERE id=${input.supersedesDocumentId} AND engagement_id=${input.engagementId} LIMIT 1`;if(!rows.length)return badRequest('Superseded document does not belong to this engagement');superseded=rows[0];}const versionLabel=superseded?nextVersion(superseded.version_label):'1.0';const code=`DOC-${randomBytes(3).toString('hex').toUpperCase()}`;
      const [row]=await sql`INSERT INTO documents(engagement_id,document_code,title,class,status,storage_key,file_name,content_type,file_size_bytes,checksum_sha256,confidential,client_visible,uploaded_by_user_id,version_label,supersedes_document_id) VALUES (${input.engagementId},${code},${input.title},${input.class||'other'},'draft',${input.storageKey},${input.fileName},${input.contentType||'application/octet-stream'},${Number(input.fileSizeBytes||0)},${input.checksumSha256||null},true,${clientVisible},${scope.access.user.id},${versionLabel},${superseded?.id||null}) RETURNING id::text`;
      await audit(request,{userId:scope.access.user.id,engagementId:input.engagementId,action:superseded?'document.version_created':'document.uploaded',entityType:'document',entityId:row.id,metadata:{documentCode:code,fileName:input.fileName,fileSizeBytes:Number(input.fileSizeBytes||0),checksumSha256:input.checksumSha256||null,clientVisible,versionLabel,supersedesDocumentId:superseded?.id||null}});return ok({id:row.id,documentCode:code,versionLabel});
    }

    if(path==='document-status'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.documentId||!input.status)return badRequest('documentId and status are required');const [d]=await sql`SELECT id::text,engagement_id::text,status,client_visible FROM documents WHERE id=${input.documentId} LIMIT 1`;if(!d||!scopeHas(scope,d.engagement_id))return forbidden();if(!role(scope,deliveryRoles))return forbidden('Document management role required');if(input.status==='approved')return conflict('Documents must be approved through the formal approval workflow');if(input.status==='superseded')return conflict('Supersession is controlled automatically when a replacement version is approved');if(d.status==='approved'&&input.status==='draft')return conflict('An approved controlled document cannot return to draft; create a new version instead');if(d.status==='superseded')return conflict('A superseded document is immutable');const clientVisible=input.clientVisible??d.client_visible;await sql`UPDATE documents SET status=${input.status},client_visible=${clientVisible},updated_at=now() WHERE id=${input.documentId}`;await audit(request,{userId:scope.access.user.id,engagementId:d.engagement_id,action:'document.status_changed',entityType:'document',entityId:input.documentId,metadata:{previousStatus:d.status,status:input.status,clientVisible}});return ok({ok:true});
    }

    if(path==='finding-update'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.findingId||!input.status)return badRequest('findingId and status are required');const [f]=await sql`SELECT id::text,engagement_id::text,status,finding_code FROM findings WHERE id=${input.findingId} LIMIT 1`;if(!f||!scopeHas(scope,f.engagement_id))return forbidden();if(!role(scope,findingRoles))return forbidden('Security delivery role required');if(input.remediationOwnerUserId){const owner=await sql`SELECT id FROM engagement_members WHERE engagement_id=${f.engagement_id} AND user_id=${input.remediationOwnerUserId} AND active=true LIMIT 1`;if(!owner.length)return badRequest('Remediation owner must be an active engagement member');}if(input.status==='accepted_risk'){const approval=await sql`SELECT id FROM approvals WHERE engagement_id=${f.engagement_id} AND entity_type='finding' AND entity_id=${String(input.findingId)} AND status='approved' LIMIT 1`;if(!approval.length)return conflict('Accepted risk requires an approved finding approval request');}
      await sql`UPDATE findings SET status=${input.status},remediation_due_at=${input.remediationDueAt||null},remediation_owner_user_id=${input.remediationOwnerUserId||null},retest_result=${input.retestResult||null},retested_at=CASE WHEN ${input.retestResult||null} IS NULL THEN NULL ELSE now() END,accepted_risk_reason=${input.acceptedRiskReason||null},accepted_by_user_id=CASE WHEN ${input.status}='accepted_risk' THEN ${scope.access.user.id} ELSE NULL END,accepted_at=CASE WHEN ${input.status}='accepted_risk' THEN now() ELSE NULL END,client_visible=${!!input.clientVisible},closed_at=CASE WHEN ${input.status} IN ('closed','false_positive') THEN now() ELSE NULL END,updated_at=now() WHERE id=${input.findingId}`;await audit(request,{userId:scope.access.user.id,engagementId:f.engagement_id,action:'finding.updated',entityType:'finding',entityId:input.findingId,metadata:{previousStatus:f.status,status:input.status,clientVisible:!!input.clientVisible,retested:!!input.retestResult,remediationOwnerUserId:input.remediationOwnerUserId||null}});return ok({ok:true});
    }

    if(path==='risk-update'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.riskId||!input.status)return badRequest('riskId and status are required');const [r]=await sql`SELECT id::text,engagement_id::text,status FROM risk_items WHERE id=${input.riskId} LIMIT 1`;if(!r||!scopeHas(scope,r.engagement_id))return forbidden();if(!role(scope,riskRoles))return forbidden('Risk management role required');if(input.ownerUserId){const owner=await sql`SELECT id FROM engagement_members WHERE engagement_id=${r.engagement_id} AND user_id=${input.ownerUserId} AND active=true LIMIT 1`;if(!owner.length)return badRequest('Risk owner must be an active engagement member');}if(input.status==='accepted'){const approval=await sql`SELECT id FROM approvals WHERE engagement_id=${r.engagement_id} AND entity_type='risk' AND entity_id=${String(input.riskId)} AND status='approved' LIMIT 1`;if(!approval.length)return conflict('Risk acceptance requires an approved risk approval request');}
      await sql`UPDATE risk_items SET status=${input.status},treatment=${input.treatment??null},treatment_plan=${input.treatmentPlan||null},owner_user_id=${input.ownerUserId||null},residual_likelihood=${input.residualLikelihood??null},residual_impact=${input.residualImpact??null},target_date=${input.targetDate||null},review_date=${input.reviewDate||null},client_visible=${!!input.clientVisible},accepted_by_user_id=CASE WHEN ${input.status}='accepted' THEN ${scope.access.user.id} ELSE NULL END,accepted_at=CASE WHEN ${input.status}='accepted' THEN now() ELSE NULL END,updated_at=now() WHERE id=${input.riskId}`;await audit(request,{userId:scope.access.user.id,engagementId:r.engagement_id,action:'risk.updated',entityType:'risk',entityId:input.riskId,metadata:{previousStatus:r.status,status:input.status,treatment:input.treatment??null,clientVisible:!!input.clientVisible,ownerUserId:input.ownerUserId||null}});return ok({ok:true});
    }

    if(path==='risk-control'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.riskId)return badRequest('riskId is required');const [r]=await sql`SELECT id::text,engagement_id::text FROM risk_items WHERE id=${input.riskId} LIMIT 1`;if(!r||!scopeHas(scope,r.engagement_id))return forbidden();if(!role(scope,riskRoles))return forbidden('Risk management role required');let controlId=input.controlId?String(input.controlId):null;if(!controlId){if(!input.framework||!input.controlCode||!input.title)return badRequest('Control definition is required');const existing=await sql`SELECT id::text FROM control_catalog WHERE framework=${input.framework} AND control_code=${input.controlCode} LIMIT 1`;if(existing.length){controlId=existing[0].id;await sql`UPDATE control_catalog SET title=${input.title},description=${input.description||null},domain=${input.domain||null},active=true WHERE id=${controlId}`;}else{const [c]=await sql`INSERT INTO control_catalog(framework,control_code,title,description,domain,active) VALUES (${input.framework},${input.controlCode},${input.title},${input.description||null},${input.domain||null},true) RETURNING id::text`;controlId=c.id;}}else{const c=await sql`SELECT id FROM control_catalog WHERE id=${controlId} AND active=true LIMIT 1`;if(!c.length)return badRequest('Selected control is unavailable');}const existingLink=await sql`SELECT id::text FROM risk_control_links WHERE risk_id=${input.riskId} AND control_id=${controlId} LIMIT 1`;let linkId:string;if(existingLink.length){linkId=existingLink[0].id;await sql`UPDATE risk_control_links SET status=${input.status||'planned'},effectiveness_notes=${input.effectivenessNotes||null},assessed_by_user_id=${scope.access.user.id},assessed_at=now() WHERE id=${linkId}`;}else{const [l]=await sql`INSERT INTO risk_control_links(risk_id,control_id,status,effectiveness_notes,assessed_by_user_id,assessed_at) VALUES (${input.riskId},${controlId},${input.status||'planned'},${input.effectivenessNotes||null},${scope.access.user.id},now()) RETURNING id::text`;linkId=l.id;}await audit(request,{userId:scope.access.user.id,engagementId:r.engagement_id,action:'risk.control_mapped',entityType:'risk',entityId:input.riskId,metadata:{controlId,status:input.status||'planned'}});return ok({linkId,controlId});
    }

    if(path==='report-update'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.reportId||!input.title||!input.reportType||!input.status)return badRequest('Required report fields are missing');const [r]=await sql`SELECT id::text,engagement_id::text,status,client_visible FROM reports WHERE id=${input.reportId} LIMIT 1`;if(!r||!scopeHas(scope,r.engagement_id))return forbidden();if(!role(scope,reportRoles))return forbidden('Report management role required');if(['final','superseded'].includes(r.status))return conflict('Final and superseded reports are immutable; create a new controlled report version');const assessment=input.assessmentId?await sql`SELECT id::text,client_visible FROM assessments WHERE id=${input.assessmentId} AND engagement_id=${r.engagement_id} LIMIT 1`:[];const document=input.documentId?await sql`SELECT id::text,client_visible,status FROM documents WHERE id=${input.documentId} AND engagement_id=${r.engagement_id} LIMIT 1`:[];if(input.assessmentId&&!assessment.length)return badRequest('Assessment does not belong to this engagement');if(input.documentId&&!document.length)return badRequest('Document does not belong to this engagement');if(input.clientVisible&&input.status!=='client_review')return conflict('A report can only be released to clients while in client review or after final approval');if(input.clientVisible&&assessment[0]&&!assessment[0].client_visible)return conflict('A client-visible report cannot reference an internal-only assessment');if(input.clientVisible&&document[0]&&!document[0].client_visible)return conflict('A client-visible report cannot attach an internal-only document');if(input.clientVisible&&document[0]&&document[0].status!=='approved')return conflict('A client-visible report can only attach an approved controlled document');
      await sql`UPDATE reports SET title=${input.title},report_type=${input.reportType},executive_summary=${input.executiveSummary||null},technical_summary=${input.technicalSummary||null},status=${input.status},assessment_id=${input.assessmentId||null},document_id=${input.documentId||null},reviewed_by_user_id=CASE WHEN ${input.status} IN ('internal_review','client_review') THEN ${scope.access.user.id} ELSE NULL END,client_visible=${!!input.clientVisible},updated_at=now() WHERE id=${input.reportId}`;await audit(request,{userId:scope.access.user.id,engagementId:r.engagement_id,action:'report.updated',entityType:'report',entityId:input.reportId,metadata:{previousStatus:r.status,status:input.status,clientVisible:!!input.clientVisible,assessmentId:input.assessmentId||null,documentId:input.documentId||null}});return ok({ok:true});
    }

    if(path==='report-version'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.reportId)return badRequest('reportId is required');const rows=await sql`SELECT * FROM reports WHERE id=${input.reportId} LIMIT 1`;const r:any=rows[0];if(!r||!scopeHas(scope,r.engagement_id))return forbidden();if(!role(scope,reportRoles))return forbidden('Report management role required');if(r.status!=='final')return conflict('Only a final report can start a controlled replacement version');const existing=await sql`SELECT id::text,version_label FROM reports WHERE supersedes_report_id=${r.id} AND status<>'superseded' LIMIT 1`;if(existing.length)return conflict(`A replacement version (${existing[0].version_label}) already exists`);const versionLabel=nextVersion(r.version_label);const [created]=await sql`INSERT INTO reports(engagement_id,assessment_id,document_id,title,report_type,status,version_label,executive_summary,technical_summary,prepared_by_user_id,client_visible,supersedes_report_id) VALUES (${r.engagement_id},${r.assessment_id},${r.document_id},${r.title},${r.report_type},'draft',${versionLabel},${r.executive_summary},${r.technical_summary},${scope.access.user.id},false,${r.id}) RETURNING id::text`;await audit(request,{userId:scope.access.user.id,engagementId:r.engagement_id,action:'report.version_created',entityType:'report',entityId:created.id,metadata:{supersedesReportId:String(r.id),versionLabel}});return ok({id:created.id,versionLabel});
    }

    if(path==='password-change'){
      const access=await accessContext();if(!access)return unauthorized();const sessionId=await getSessionId();if(!sessionId)return unauthorized();const input=await body(request);if(!input.currentPassword||!input.newPassword)return badRequest('Current and new passwords are required');if(String(input.newPassword).length<12)return badRequest('New password must be at least 12 characters');const rows=await sql`SELECT password_hash FROM user_passwords WHERE user_id=${access.user.id} LIMIT 1`;if(!rows.length||!(await compare(input.currentPassword,rows[0].password_hash)))return unauthorized('Current password is incorrect');const newHash=await hash(input.newPassword,12);await sql`UPDATE user_passwords SET password_hash=${newHash},updated_at=now() WHERE user_id=${access.user.id}`;let revokedSessions=0;if(input.revokeOtherSessions){const deleted=await sql`DELETE FROM sessions WHERE user_id=${access.user.id} AND id<>${sessionId} RETURNING id`;revokedSessions=deleted.length;}await audit(request,{userId:access.user.id,action:'security.password_changed',entityType:'user',entityId:access.user.id,metadata:{revokedOtherSessions:!!input.revokeOtherSessions,revokedSessions}});return ok({ok:true,revokedSessions});
    }

    if(path==='push-subscription'){
      const access=await accessContext();if(!access)return unauthorized();const input=await body(request);if(!input.identity||!input.action)return badRequest('identity and action are required');if(input.action==='remove')await sql`UPDATE push_subscriptions SET active=false,updated_at=now() WHERE user_id=${access.user.id} AND identity=${input.identity}`;else await sql`INSERT INTO push_subscriptions(user_id,identity,subscription,platform,active) VALUES (${access.user.id},${input.identity},${sql.json(input.subscription||{})},${input.platform||null},true) ON CONFLICT(user_id,identity) DO UPDATE SET subscription=EXCLUDED.subscription,platform=EXCLUDED.platform,active=true,updated_at=now()`;return ok({ok:true},{headers:{'Cache-Control':'no-store'}});
    }

    if(path==='srs-import'){
      const access=await accessContext();if(!access)return unauthorized();if(!access.isPlatformAdmin)return forbidden('Administrator access required');const input=await body(request);if(!Array.isArray(input.rows)||!input.rows.length)return badRequest('Import rows are required');const nums=input.rows.map((r:any)=>Number(r.sectionNumber));if(new Set(nums).size!==nums.length)return badRequest('Duplicate section numbers exist in this import batch');for(const r of input.rows){const ref=`SRS-${String(r.sectionNumber).padStart(4,'0')}`;if(r.sectionRef&&r.sectionRef!==ref)return badRequest(`Section ${r.sectionNumber} reference must remain ${ref}`);}
      await sql.begin(async tx=>{for(const r of input.rows)await tx`UPDATE srs_sections SET phase_number=${r.phaseNumber??null},section_ref=${`SRS-${String(r.sectionNumber).padStart(4,'0')}`},title=${r.title||null},requirement_text=${r.requirementText},status=${r.status},implementation_ref=${r.implementationRef||null},verification_ref=${r.verificationRef||null},notes=${r.notes||null},source_file_name=${input.sourceFileName||null},source_file_sha256=${input.sourceFileSha256||null},source_imported_at=CASE WHEN ${input.sourceFileSha256||null} IS NULL THEN NULL ELSE now() END,source_imported_by_user_id=CASE WHEN ${input.sourceFileSha256||null} IS NULL THEN NULL ELSE ${access.user.id} END,source_origin=CASE WHEN ${input.sourceFileSha256||null} IS NULL THEN NULL ELSE ${input.sourceOrigin||'imported_source'} END,baseline_version=${input.baselineVersion||null},updated_at=now() WHERE section_number=${r.sectionNumber}`;});
      await audit(request,{userId:access.user.id,action:'srs.bulk_import',entityType:'srs_section',metadata:{count:input.rows.length,firstSection:Math.min(...nums),lastSection:Math.max(...nums),sourceFileName:input.sourceFileName||null,sourceFileSha256:input.sourceFileSha256||null,sourceOrigin:input.sourceOrigin||'imported_source',baselineVersion:input.baselineVersion||null}});
      const phases=await sql`SELECT phase_number,count(*)::int AS assigned,count(*) FILTER(WHERE status='verified')::int AS verified,count(*) FILTER(WHERE status IN ('in_progress','implemented','verified'))::int AS active FROM srs_sections WHERE phase_number IS NOT NULL GROUP BY phase_number`;for(const p of phases as any[]){const completion=p.assigned?Number(((p.verified/p.assigned)*100).toFixed(2)):0;const status=p.assigned>0&&p.verified===p.assigned?'verified':p.active>0?'in_progress':'planned';await sql`UPDATE srs_phases SET status=${status},completion_percent=${completion},updated_at=now() WHERE phase_number=${p.phase_number}`;}return ok({updated:input.rows.length,firstSection:Math.min(...nums),lastSection:Math.max(...nums)});
    }

    if(path==='support-assign'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.ticketId)return badRequest('ticketId is required');const [t]=await sql`SELECT id::text,engagement_id::text,assigned_user_id::text,ticket_code,title FROM support_tickets WHERE id=${input.ticketId} LIMIT 1`;if(!t)return notFound('Ticket not found');if(!role(scope,deliveryRoles))return forbidden('Support management role required');if(t.engagement_id&&!scope.access.isPlatformAdmin&&!scopeHas(scope,t.engagement_id))return forbidden();if(input.assignedUserId){const eligible=t.engagement_id?await sql`SELECT em.id FROM engagement_members em JOIN organization_memberships m ON m.user_id=em.user_id JOIN organizations o ON o.id=m.organization_id JOIN users u ON u.id=em.user_id WHERE em.engagement_id=${t.engagement_id} AND em.user_id=${input.assignedUserId} AND em.active=true AND m.active=true AND o.active=true AND o.kind='internal' AND u.active=true LIMIT 1`:await sql`SELECT m.id FROM organization_memberships m JOIN organizations o ON o.id=m.organization_id JOIN users u ON u.id=m.user_id WHERE m.user_id=${input.assignedUserId} AND m.active=true AND o.active=true AND o.kind='internal' AND u.active=true LIMIT 1`;if(!eligible.length)return badRequest('Selected assignee is not eligible for this ticket');}await sql`UPDATE support_tickets SET assigned_user_id=${input.assignedUserId||null},status=CASE WHEN ${input.assignedUserId||null} IS NULL THEN status ELSE 'in_progress' END,updated_at=now() WHERE id=${input.ticketId}`;if(input.assignedUserId&&String(input.assignedUserId)!==String(scope.access.user.id))await sql`INSERT INTO notifications(user_id,type,title,body,url) VALUES (${input.assignedUserId},'support_assignment',${`Assigned ${t.ticket_code}`},${`You were assigned support ticket: ${t.title}`},${`/portal/support/${t.id}`})`;await audit(request,{userId:scope.access.user.id,engagementId:t.engagement_id,action:'support_ticket.assigned',entityType:'support_ticket',entityId:input.ticketId,metadata:{previousAssignedUserId:t.assigned_user_id,assignedUserId:input.assignedUserId||null}});return ok({ok:true});
    }

    if(path==='support-status'){
      const scope=await authorizedEngagementScope();if(!scope)return unauthorized();const input=await body(request);if(!input.ticketId||!input.status)return badRequest('ticketId and status are required');const [t]=await sql`SELECT id::text,engagement_id::text,opened_by_user_id::text,ticket_code,status FROM support_tickets WHERE id=${input.ticketId} LIMIT 1`;if(!t)return notFound('Ticket not found');const actor=String(scope.access.user.id);if(!role(scope,deliveryRoles)&&!(t.opened_by_user_id===actor&&input.status==='closed'))return forbidden('You do not have permission to change this ticket status');await sql`UPDATE support_tickets SET status=${input.status},resolved_at=CASE WHEN ${input.status} IN ('resolved','closed') THEN now() ELSE NULL END,updated_at=now() WHERE id=${input.ticketId}`;if(t.opened_by_user_id!==actor)await sql`INSERT INTO notifications(user_id,type,title,body,url) VALUES (${t.opened_by_user_id},'support_status',${`${t.ticket_code} status updated`},${`Your support ticket is now ${String(input.status).replaceAll('_',' ')}.`},${`/portal/support/${t.id}`})`;await audit(request,{userId:actor,engagementId:t.engagement_id,action:'support_ticket.status_changed',entityType:'support_ticket',entityId:input.ticketId,metadata:{status:input.status}});return ok({ok:true});
    }

    return null;
  }catch(error){console.error('Detailed portal POST failed',path,error);return serverError(error);}
}
